<!DOCTYPE html>
<html lang="en">
<head>
    <title>ESNAAD Real Estate Development L.L.C.</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.3.5/jspdf.min.js"></script>
    <style>
        @font-face {
            font-family: 'Optima';
            src: local('Optima'), url({{asset('fonts/OptimaLite.woff')}}) format('opentype');
        }
        
        body{
            font-family: 'Optima', sans-serif;
            margin-top:20px;
            background:#000;
        }

        .card-footer-btn {
            display: flex;
            align-items: center;
            /* border-top-left-radius: 0!important; */
            /* border-top-right-radius: 0!important; */
        }

        .text-uppercase-bold-sm {
            text-transform: uppercase!important;
            font-weight: 500!important;
            letter-spacing: 2px!important;
            font-size: .85rem!important;
        }
        
        .justify-content-center {
            justify-content: center!important;
        }


        .card {
            position: relative;
            display: flex;
            flex-direction: column;
            min-width: 0;
            word-wrap: break-word;
            background-color: #fff;
            /* background-clip: border-box; */
            /* border: 1px solid rgba(30,46,80,.09); */
            /* border-radius: 0.25rem; */
            /* box-shadow: 0 20px 27px 0 rgb(0 0 0 / 5%); */
        }

        .p-5 {
            padding: 3rem!important;
        }

        .card-body {
            flex: 1 1 auto;
            padding: 1.5rem 1.5rem;
        }

        tbody, td, tfoot, th, thead, tr {
            border-color: inherit;
            border-style: solid;
            border-width: 0;
        }

        .table td, .table th {
            border-bottom: 0;
            border-top: 1px solid #edf2f9;
        }

        .table>:not(caption)>*>* {
            padding: 0rem 1rem;
            background-color: var(--bs-table-bg);
            border-bottom-width: 1px;
            box-shadow: inset 0 0 0 9999px var(--bs-table-accent-bg);
        }

        .px-0 {
            padding-right: 0!important;
            padding-left: 0!important;
        }

        .table thead th, tbody td, tbody th {
            vertical-align: middle;
        }

        tbody, td, tfoot, th, thead, tr {
            border-color: inherit;
            border-style: solid;
            border-width: 0;
        }

        .mt-5 {
            margin-top: 3rem!important;
        }

        .heading-p{
            font-size: 12px;
        }

        .body-p{
            font-size: 12px;
        }

        .body-table-p{
            font-size: 12px;
            text-align: center !important;
        }
        
        .body-heading {
            font-size: 24px;
            text-align:center;
        }

        .body-p-sub{
            font-size: 10px;

        }

        .page-break-before {
            page-break-before: always;
        }





    </style>
</head>
<body >


    <div class="container mt-6 mb-7 px-0">
        <div class="row justify-content-center">
        <div class="col-lg-12 col-xl-7">
            <div class="card">
                <div class="card-header px-5" style="background-color: #fff;">
                    <div class="d-flex justify-content-between">
                        <div class="float-left my-auto">
                            <h1 style="font-size: 24px" class="m-0">SALES OFFER</h1>
                        </div>
                        <div class="">
                            <img src="{{ asset('logo-dark.png')}}" alt="" height="40">
                        </div>
                    </div>
                    <div class="d-flex justify-content-between mt-4">
                        <div class="float-left my-auto">
                        <p class="heading-p m-0">{{ \Carbon\Carbon::now()->format('d.m.Y') }}</p>
                        </div>
                        <div class="">
                            <p class="heading-p m-0">Generated by: {{ Auth::user()->name }}</p>
                        </div>
                    </div>
                    <div class="mt-4">
                        <p class="heading-p m-0 mt-3">Dear Customer,</p>
                        <p class="heading-p m-0 mt-1">
                            Based on our recent discussions and understanding of your specific needs, the below listed projects have been catered.
                        </p>
                    </div>
                </div>
                <div class="card-body p-5">
                
                    <table class="table table-bordered">
                        <tr>
                            <td>
                                <span class="body-table-p font-weight-bold">Project Name</span>
                            </td>

                            <td>
                                <span class="body-table-p font-weight-bold">Unit Name</span>
                            </td>

                            <td>
                                <span class="body-table-p font-weight-bold">Completion year</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="body-table-p">{{ $unit->project->name }}</span>
                            </td>
                            <td>
                                <span class="body-table-p">{{ $unit->name }}</span>
                            </td>
                            <td>
                                <span class="body-table-p">{{ $unit->project->handover }}</span>
                            </td>
                        </tr>
                    </table>

                    <table class="table table-bordered">
                        
                        <tr>
                            <td>
                                <span class="body-table-p font-weight-bold">Bedrooms</span>
                            </td>
                            <td>
                                <span class="body-table-p font-weight-bold">Total Area</span>
                            </td>
                            <td>
                                <span class="body-table-p font-weight-bold">Balcony Area</span>
                            </td>
                            <td>
                                <span class="body-table-p font-weight-bold">Price (AED)</span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <span class="body-table-p">{{ $unit->bedroom }}</span>
                            </td>

                            <td>
                                <span class="body-table-p">{{ number_format($unit->unit_size_range) }}</span>
                            </td>

                            <td>
                                <span class="body-table-p">{{ number_format($unit->outdoor_area) }}</span>
                            </td>

                            <td>
                                <span class="body-table-p">{{ number_format($unit->unit_price) }}</span>
                            </td>
                        </tr>
                    </table>

                    <div class="">
                        <p class="body-p-sub m-0">*Applicable fees to Dubai Land Department are: 4% of the property net price + AED 3,150 (VAT inc.) oqood fee</p>
                        <p class="body-p-sub m-0">*Prices and availability are subject to change without notice</p>
                        <p class="body-p-sub m-0">*The Estimated Completion Date is a mere estimate and subject to change from time to time</p>
                    </div>

                    <div class="border-top border-gray-200 pt-4 pb-4 mt-4">
                        <p class="body-heading m-0">Payment Plans</p>
                    </div>
                    

                    <table class="table table-bordered"> 
                        <tr>
                            <td>
                                <span class="body-table-p font-weight-bold">Installment</span>
                            </td>
                            <td>
                                <span class="body-table-p font-weight-bold">Milestone</span>
                            </td>
                            <td>
                                <span class="body-table-p font-weight-bold">Percentage</span>
                            </td>
                            <td>
                                <span class="body-table-p font-weight-bold">Amount</span>
                            </td>
                        </tr>
                        @foreach($unit_paymentplan[0]->unit_paymentplan_files as $data)
                            <tr>
                                <td>
                                    <span class="body-table-p">{{ $loop->index+1 }}</span>
                                </td>

                                <td>
                                    <span class="body-table-p">{{ $data->name }}</span>
                                </td>

                                <td>
                                    <span class="body-table-p">{{ $data->percentage }}</span>
                                </td>

                                <td>
                                    <span class="body-table-p">{{ $data->amount }}</span>
                                </td>

                            </tr>
                        @endforeach
                    </table>


                    <div class="page-break-before border-top border-gray-200 pt-4 pb-4 mt-4">
                        <p class="body-heading m-0">Floor Plans</p>
                    </div>

                    @if(isset($unit_floorplan))
                        @if($unit_floorplan[0]->unit_floorplan_files->count() > 0)
                            @foreach($unit_floorplan[0]->unit_floorplan_files as $file)
                            <div style="width: 100%; text-align: center;">
                                <img src="{{ asset('uploads/units/floorplans/'.$unit_floorplan[0]->id.'/'.$file->name)}}" class="mx-auto text-center" style="width: 80%; padding: 35px; margin-bottom: 10px; height: 100%; z-index: -19;">
                            </div>
                            @endforeach
                        @endif
                    @endif

                    
                </div>
            </div>
        </div>
    </div>

    
</body>

<script>
var doc = new jsPDF();
    var specialElementHandlers = {
        '#editor': function (element, renderer) {
            return true;
        }
    };

    $('#cmd').click(function () {
        doc.fromHTML($('#content').html(), 15, 15, {
            'width': 170,
                'elementHandlers': specialElementHandlers
        });
        doc.save('sample-file.pdf');
    });
</script>
</html>
